client_id: ZRav5VnmUZPsY2YTaVsNvhuvYVK93-DR
client_secret: apdZqjz0q0ORR6zIculLVK-FR4fxdYSxTyzzhd1v
redirect_url: http://localhost:8000/uber/connect
scopes:
    - profile
    - history
    - places
    - request
    - request_receipt
    - all_trips
